---
name: 'Actions AWS Host Service'
description: 'Deploy and manage systemd services on EC2 instances using SSM'
inputs:
  name:
    description: 'Service name'
    required: true
  status:
    description: 'Service status (enabled/disabled)'
    required: true
    default: 'enabled'
  definition:
    description: 'Service definition file path (relative to artifacts)'
    required: true
  targets:
    description: 'Target selection criteria in format tag:KEY:VALUE (one per line). Example: tag:Environment:DEV'
    required: true
  working-directory:
    description: 'Where to extract artifacts on target instances'
    required: true
    default: '/home/ssm-user'
  artifacts:
    description: 'Folder containing deployment artifacts'
    required: true
  action:
    description: "Desire outcome: apply, plan or destroy"
    required: false
    default: "apply"
  setup-aws-cli:
    description: "Setup AWS CLI"
    required: false
    default: "false"
  run-association:
    description: "Run SSM association immediately after creation"
    required: false
    default: "false"
  wait-for-association-id:
    description: "Wait for this association ID to complete before running this action"
    required: false
    default: ""

outputs:
  bucket:
    description: "S3 bucket name for artifacts"
    value: ${{ steps.tf-outputs.outputs.bucket }}
  document:
    description: "SSM document ARN"
    value: ${{ steps.tf-outputs.outputs.document }}
  role_name:
    description: "IAM role name"
    value: ${{ steps.tf-outputs.outputs.role_name }}
  association_id:
    description: "SSM Association ID"
    value: ${{ steps.tf-outputs.outputs.association_id }}

runs:
  using: "composite"

  steps:
    - name: Wait for previous association
      if: inputs.wait-for-association-id != ''
      shell: bash
      run: |
        echo "Waiting for association ${{ inputs.wait-for-association-id }} to complete..."
        aws ssm describe-association-executions \
          --association-id ${{ inputs.wait-for-association-id }} \
          --max-results 5 \
          --query "AssociationExecutions[0].Status" \
          --output text

    - name: init
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        terraform init -reconfigure \
          -backend-config="bucket=${{ env.TF_BACKEND_s3 }}" \
          -backend-config="dynamodb_table=${{ env.TF_BACKEND_dynamodb }}" \
          -backend-config="key=${{ inputs.name }}"

    - name: run action
      id: tf-action
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        ACTION: ${{ inputs.action }}
        ACTION_ARGS: ${{ inputs.action != 'plan' && '-auto-approve' || '' }}
        TF_VAR_name: ${{ inputs.name }}
        TF_VAR_status: ${{ inputs.status }}
        TF_VAR_working_directory: ${{ inputs.working-directory }}
        TF_VAR_artifact_path: ${{ github.sha }}-${{ github.run_attempt }}
        TF_VAR_definition_file: ${{ inputs.definition }}
        TF_VAR_targets: ${{ inputs.targets }}
        TF_VAR_artifacts_path: ${{ github.workspace }}/${{ inputs.artifacts }}
        TF_VAR_setup_aws_cli: ${{ inputs.setup-aws-cli }}
      run: terraform ${{ env.ACTION }} ${{ env.ACTION_ARGS }}

    - name: get terraform outputs
      id: tf-outputs
      if: inputs.action != 'destroy'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        BUCKET=$(terraform output -raw bucket)
        DOCUMENT=$(terraform output -raw document)
        ROLE_NAME=$(terraform output -raw role_name)
        ASSOCIATION_ID=$(terraform output -raw association_id)
        echo "bucket=$BUCKET" >> $GITHUB_OUTPUT
        echo "document=$DOCUMENT" >> $GITHUB_OUTPUT
        echo "role_name=$ROLE_NAME" >> $GITHUB_OUTPUT
        echo "association_id=$ASSOCIATION_ID" >> $GITHUB_OUTPUT
    
    - name: run association immediately
      if: inputs.run-association == 'true' && inputs.action != 'destroy'
      shell: bash
      run: |
        ASSOCIATION_ID=$(terraform -chdir=${{ github.action_path }} output -raw association_id)
        echo "Running association $ASSOCIATION_ID immediately..."
        aws ssm start-associations-once --association-ids $ASSOCIATION_ID
